### PR TITLE
Minor Bugfixes and enhancement

### PR DESCRIPTION
**Pull request by knit-pay**
`static` was missing in `get_payment_method_from_submission_data` function
set default `config_id` to `pronamic_pay_config_id`

### CODE REVIEW

**Comment by rvdsteege** [comment]
The configuration setting has no default intentionally. Without a configuration being set, the default gateway configuration from the Pronamic Pay plugin settings is being used:

- https://github.com/wp-pay-extensions/ninjaforms/blob/42992717ba5e3bedbf854ebb5dad4f7ccb97a3e0/src/NinjaFormsHelper.php#L66-L84

If we would set a default gateway configuration in the Ninja Forms action, all Ninja Forms actions need to be updated if a user wants to change the default gateway configuration for all forms — instead of just updating the default gateway configuration in the general plugin settings.

**Comment by knit-pay** [comment]
ok, thanks for the information. In that case, I have a suggestion, we can add the below code at this line to make it more clear for user that if they will use this option then default gateway will be picked.

```
		    if (0 === $value){
		        $label = __( 'Default Gateway', 'pronamic_ideal' );
		    }
```

https://github.com/wp-pay-extensions/ninjaforms/blob/42992717ba5e3bedbf854ebb5dad4f7ccb97a3e0/src/PaymentGateway.php#L161

May I raise a new pull request with this change?

**Comment by knit-pay** [comment]
@rvdsteege
Have you checked my last recommendation, may I implement it?

**Comment by remcotolsma** [comment]
Fixed in e7be31df10c6bb55f197ca32b674c00f596b7967 and 972b95258559a430511b7561c5c50aa91d67e75e.

**Pull request closed without merging**
